### ISSUE TITLE
EXC_BAD_ACCESS on iPhone5, iOS8.4, Xcode7-beta5, Swift 2.0

### ISSUE THREAD

**Issue by basvankuijck** [KyoheiG3/DynamicBlurView#3]
```
<Error>: copy_read_only: vm_copy failed: status 1.
```

Xcode referred to line 340 of `DynamicBlurView.swift`:

```
if let bitmap = CGBitmapContextCreateImage(bitmapContext) {
```

I don't do anything fancy with the DynamicBlurView.
Stacktrace:

```
#0  0x3a670ae6 in _platform_memmove ()
#2  0x2bb09b6a in CGBitmapContextCreateImage ()
#3  0x0032ac78 in ext.DynamicBlurView.ObjectiveC.UIImage.blurredImage (ObjectiveC.UIImage(CoreGraphics.CGFloat, iterations : Swift.Int, ratio : CoreGraphics.CGFloat, blendColor : Swift.Optional<ObjectiveC.UIColor>) -> Swift.ImplicitlyUnwrappedOptional<ObjectiveC.UIImage> at /.../DynamicBlurView/DynamicBlurView.swift:340
#4  0x0032afd8 in @objc ext.DynamicBlurView.ObjectiveC.UIImage.blurredImage (ObjectiveC.UIImage)(CoreGraphics.CGFloat, iterations : Swift.Int, ratio : CoreGraphics.CGFloat, blendColor : Swift.Optional<ObjectiveC.UIColor>) -> Swift.ImplicitlyUnwrappedOptional<ObjectiveC.UIImage> ()
#5  0x0032bce8 in DynamicBlurView.DynamicBlurView.((setCaptureImage in _2044C6510BFEB36C5566C936E3D26E26) (DynamicBlurView.DynamicBlurView) -> (ObjectiveC.UIImage, radius : CoreGraphics.CGFloat) -> ()).(closure #1) at /.../DynamicBlurView/DynamicBlurView.swift:197    
#6  0x00328854 in DynamicBlurView.DynamicBlurView.(setCaptureImage in _2044C6510BFEB36C5566C936E3D26E26) (DynamicBlurView.DynamicBlurView)(ObjectiveC.UIImage, radius : CoreGraphics.CGFloat) -> () at /.../DynamicBlurView/DynamicBlurView.swift:207
#7  0x0032bac4 in DynamicBlurView.DynamicBlurView.(displayLayer (DynamicBlurView.DynamicBlurView) -> (ObjectiveC.CALayer) -> ()).(closure #1) at /.../DynamicBlurView/DynamicBlurView.swift:168
```

The problem only occurs on my iPhone. The simulator works fine though.

Resolved in #4

**Comment by KyoheiG3** [comment]
Fixed in https://github.com/KyoheiG3/DynamicBlurView/pull/4
